version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/business_nexus
      - JWT_SECRET=devsecret
      - CLIENT_ORIGIN=http://localhost:5173
      - PORT=4000
    ports: ["4000:4000"]
    depends_on: [mongo]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:4000/api
      - VITE_SOCKET_URL=http://localhost:4000
    ports: ["5173:5173"]
    depends_on: [server]

volumes:
  mongo_data:
