name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install server
        working-directory: server
        run: npm ci
      - name: Install client
        working-directory: client
        run: npm ci
      - name: Build client
        working-directory: client
        run: npm run build
